train_size: 0.75

batch_size: 32
epochs: 50
learning_rate: 0.001

image_name_column_keyword: 'image'
label_column_keyword: 'label'

model: 'inception'

inception_layers_to_unfreeze : [
    'Mixed_4a',
    'Mixed_4b',
    'Mixed_5b',
    'Mixed_5c',
    'Mixed_6a',
    'Mixed_6b',
    'Mixed_6c',
    'Mixed_7a',
    'Mixed_7b',
    'Mixed_7c',
    'avgpool',
    'aux_logits',
    'con2d_1a',
    'fc'
]

efficientnetb4_layers_to_unfreeze : [
    'features[6]',
    'features[7]',
    'features[8]',
    'classifier',
]